version: 0
metadata:
  name: Example Add-on
  description: Example Add-on CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Example Add-on Lint Tests
      description: Example Add-on Lint Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "standard8/example-addon-repo-lint:2016082401.ca24710db69a"
      command:
        - "/bin/bash"
        - "-lc"
        - "git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.head.repo.branch}} && npm install && npm run lint"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
      treeherder:
        jobKind: "test"
        machine:
          platform: "lint"
        symbol: "ES"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Example Add-on Unit Tests
      description: Example Add-on Unit Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    # Note: If you get an error such as "You didn't give the task-graph scopes
    # allowing it define tasks on the queue", then you need to get permissions
    # added for this scope. See [the taskcluster doc](docs/Taskcluster.md)
    # for more detail.
    scopes:
      - secrets:get:repo:github.com/mozilla/example-addon-repo:pull-request
    payload:
      env:
        NEED_WINDOW_MANAGER: true
      features:
        taskclusterProxy: true
      maxRunTime: 1200
      image: "standard8/example-addon-repo-functional:2016082501.01748a2b1a46"
      command:
        - "/bin/bash"
        - "-lc"
        - "./bin/setup.sh && curl -O https://ftp.mozilla.org/pub/firefox/releases/48.0.2/linux-x86_64/en-US/firefox-48.0.2.tar.bz2 && tar xfj *.bz2 && git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.head.repo.branch}} && npm install && COVERALLS_REPO_TOKEN=`python scripts/get_secret.py` FIREFOX_BIN=~/firefox/firefox npm run test:karma"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
      treeherder:
        jobKind: "test"
        machine:
          platform: "lint"
        symbol: "ES"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Example Add-on Functional Tests
      description: Example Add-on Functional Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      env:
        NEED_WINDOW_MANAGER: true
      maxRunTime: 1200
      image: "standard8/example-addon-repo-functional:2016082501.01748a2b1a46"
      command:
        - "/bin/bash"
        - "-lc"
        - "./bin/setup.sh && curl -O https://ftp.mozilla.org/pub/firefox/releases/48.0.2/linux-x86_64/en-US/firefox-48.0.2.tar.bz2 && tar xfj *.bz2 && git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.head.repo.branch}} && npm install && FIREFOX_BINARY=~/firefox/firefox npm run test:func"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
      treeherder:
        jobKind: "test"
        machine:
          platform: "lint"
        symbol: "ES"
